### ISSUE TITLE
Please add API schema documentation

### ISSUE THREAD

**Issue by lumpidu** [mideind/Yfirlestur#10]
Currently, it's not easy to undestand, what the JSON response exactly means. It would be helpful to get a documentation of the key-value pairs. E.g. in the returned tokens, what means the key `x` ? One could also argue, that `x` is not a very good name. 

Accordingly, the question is, if this API is going to undertake another revision or if it's supposed to be the final API until milestone M9 ?

**Comment by vesteinn** [comment]
Thanks, we agree this could be better documented, k refers to kind which is documented here in the Tokenizer package [https://github.com/mideind/Tokenizer#the-kind-property](https://github.com/mideind/Tokenizer#the-kind-property) and x is the token text of the input. Other than that we refer to the documentation in the README at [https://github.com/mideind/Yfirlestur#https-api](https://github.com/mideind/Yfirlestur#https-api) We are not planning to revise this API in the near future.
