### ISSUE TITLE
Json support doesn't accept UTF-8 encoding

### ISSUE THREAD

**Issue by Kristober** [mideind/Yfirlestur#15]
UTF-8 encoding is the default when dealing with json data for API's. Having support for it would be helpful.

`curl -d @example.json https://yfirlestur.is/correct.api --header "Content-Type: application/json"` works as intended but as soon as I try to add `charset=utf-8` I get the response:
```json
{"reason":"Empty request","valid":false}
```
I have the same issue when using a openapi generated API.
```http
Accept: application/json
Content-Type: application/json; charset=utf-8
Content-Length: 69
Host: 10.0.2.2:5002
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/4.9.3
```

**Comment by sveinbjornt** [comment]
Fixed with 8f66be976fb7f1486bd1824dde061d14d2f7ce5a  and deployed to yfirlestur.is
