### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by Kristober** [mideind/Yfirlestur#6]
Is there no support for making a post request with the data in a Json format? If not can we expect it in the future?

I made post requests with curl and through postman using Json data without success.

**Comment by vthorsteinsson** [comment]
Hi @Kristober ! Currently, we only support plain text or form-encoded input. The place to add additional input formats would be around line 134 in `/routes/__init__.py`. You are welcome to submit a pull request, or alternatively tell us what JSON layout would be most useful, and we can look into implementing it.

**Comment by Kristober** [comment]
Hi @vthorsteinsson, JSON layout as in horizontal or vertical? I was thinking of something very basic e.g. 
```json
{
    "text":"Manninum á verkstæðinu vantar hamar"
}
```
This would be a nice to have feature for us so we can reuse components and an http-client built in kotlin that don't play nice when we try to use anything other than json.

**Comment by vthorsteinsson** [comment]
OK, understood. You are not asking for something like:

```
{
   text: [
     "Fyrsta efnisgrein.",
     "Önnur efnisgrein er hér. Hún inniheldur margar málsgreinar.",
      "Þriðja efnisgrein."
   ]
}
```

**Comment by Kristober** [comment]
Actually, the layout you described is more suited after giving it some thought, It would enable us to send multiple sentences in a request.

Also out of **curiosity**, are there any options not listed in the readme that control the kind of corrections done? If not, is there a plan to control the kind of corrections like basic/full so that we could expect similar output like with GreynirCorrect.

**Comment by Kristober** [comment]
@vthorsteinsson I would like to add a suggestion. 

There seems to be a lack of description as to how the API can be used as well as the response being undescriptive e.g. sending a post request with JSON data gives a 200 OK response with the JSON object {"reason":"Empty request","valid":false}. At first glance the request appears to be invalid because it's a empty request, not because its contents is embeded in an JSON object. 

Adding a small section to the README describing the API would be helpful.

**Comment by lumpidu** [comment]
@vthorsteinsson If I may cite the SÍM Software Development Standards, section 5.3, this service should actually implement JSON with RestFul, right ?

**Comment by sveinbjornt** [comment]
These improvements have now been deployed to production on https://yfirlestur.is
